services:
  node1:
    build: .
    command: ["--node-id=1", "--grpc-port=50071", "--http-port=3000", "--peers=2=node2:50071,3=node3:50071", "--peer-http=1=node1:3000,2=node2:3000,3=node3:3000"]
    ports:
      - "3001:3000"
    volumes:
      - ./data/node1:/app/data
    networks:
      - aegian-net

  node2:
    build: .
    command: ["--node-id=2", "--grpc-port=50071", "--http-port=3000", "--peers=1=node1:50071,3=node3:50071", "--peer-http=1=node1:3000,2=node2:3000,3=node3:3000"]
    ports:
      - "3002:3000"
    volumes:
      - ./data/node2:/app/data
    networks:
      - aegian-net

  node3:
    build: .
    command: ["--node-id=3", "--grpc-port=50071", "--http-port=3000", "--peers=1=node1:50071,2=node2:50071", "--peer-http=1=node1:3000,2=node2:3000,3=node3:3000"]
    ports:
      - "3003:3000"
    volumes:
      - ./data/node3:/app/data
    networks:
      - aegian-net

networks:
  aegian-net:
    driver: bridge